### ISSUE TITLE
Bug: A game that happened already is not showing the results at home

### ISSUE THREAD

**Issue by willianjusten** [willianjusten/nba-remix#57]
There's one game that this is happening, we just need to debug (see the API response and understand what's happening there).

How to do it:

- Go to the date (02 March 2022)
- Comment the [Index function here](https://github.com/willianjusten/nba-remix/blob/main/app/routes/%24date.tsx#L44-L57) and it should
- Refresh the page and you'll be able to see the whole JSON coming from the API
- The component that is behaving weird is the [GameCard](https://github.com/willianjusten/nba-remix/blob/main/app/components/GameCard/index.tsx), check the data coming and what's being done inside the card, you'll find out the issue

![image](https://user-images.githubusercontent.com/3991845/156574414-5ea16867-6135-4bda-ad2e-eaa5190436b5.png)

**Comment by qzw881130** [comment]
> Daaaamn, that's a bug from their API!! We can't do anything =/
> 
> http://data.nba.net/prod/v2/20220302/scoreboard.json

me too

**Comment by willianjusten** [comment]
They changed the API so it's not working anymore. I'll need to adapt to a new one but I don't have time now...
