### ISSUE TITLE
Don't show details link if game hasn't started

### ISSUE THREAD

**Issue by jonrcrowell** [willianjusten/nba-remix#75]
![image](https://user-images.githubusercontent.com/14331191/157374331-7d94180d-5515-4322-8eab-58697d3ce8ec.png)

**Comment by willianjusten** [comment]
This one happens by design, let's suppose someone wants to see all the details as soon as the game starts, he can open the page and let it there, this page is updated with revalidate, so when he gets back to the page, if the game started, he'll see the details already.
