### ISSUE TITLE
Allow user to favorite their team

### ISSUE THREAD

**Issue by jonrcrowell** [willianjusten/nba-remix#76]
Show favorite team scores first
If team is in the Western Conference, show standings for Western Conference first

For example, my favorite team is the Dallas Mavericks. I would like to see the Mavericks games first, and the Western Conference standings ahead of the Eastern.

**Comment by jonrcrowell** [comment]
This will be easier to implement once the user profile page is implemented (#6 )

**Comment by willianjusten** [comment]
Closing this one in order to leverage the discussion on #102
