### ISSUE TITLE
App crashes displaying not started game

### ISSUE THREAD

**Issue by klaytonfaria** [willianjusten/nba-remix#80]
App crashes displaying not started game stats

Screenshots

<img width="1139" alt="Screenshot 2022-03-10 at 13 52 23" src="https://user-images.githubusercontent.com/1502981/157677982-0cc6a52b-7f4c-47ef-ad75-cc68b4705aa4.png">

**Comment by willianjusten** [comment]
This was fixed here [f5862a9](https://github.com/willianjusten/nba-remix/commit/f5862a9e15b5f1ad7b7c8d6d074a5ba52429208b)
